# Generated by Django 4.2.6 on 2023-10-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_emailsignincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('movie_code', models.CharField(max_length=255)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('nation', models.CharField(blank=True, max_length=100, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
